### ISSUE TITLE
Example code not working on Herkulex 0402

### ISSUE THREAD

**Issue by singaramv** [eschneider1992/HerkulexForTeensy#1]
Hi Eric,

I am trying to use Teensy 3.2 to control Herkulex 0402. I am facing issues when I run the "MEGA_one_motor_move_angle.ino" example code. Herkulex.moveOneAngle(n, -100, 1000, LED_BLUE); function doesn't work. The motor shows error with red light blinking. 

When I try to set the motor led color using this program "MEGA_Simple_led_green.ino" it works fine.

Appreciate if you could kindly help to resolve this issue.

Thank you!

**Comment by eschneider1992** [comment]
Hello,

I'm not actually a maintainer for this code, I used it a couple of years ago for a personal project. The code came originally from here: http://robottini.altervista.org/dongbu-herkulex-arduino-library-2
